package com.example.attendance.entity;

import java.util.Date;

public class Apply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Long applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.user_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.apply_type
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String applyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.apply_state
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String applyState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.apply_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.process_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Date processDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_apply.approver_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String approverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.apply_id
     *
     * @return the value of tbl_apply.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Long getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.apply_id
     *
     * @param applyId the value for tbl_apply.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.user_id
     *
     * @return the value of tbl_apply.user_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.user_id
     *
     * @param userId the value for tbl_apply.user_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.apply_type
     *
     * @return the value of tbl_apply.apply_type
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getApplyType() {
        return applyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.apply_type
     *
     * @param applyType the value for tbl_apply.apply_type
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplyType(String applyType) {
        this.applyType = applyType == null ? null : applyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.apply_state
     *
     * @return the value of tbl_apply.apply_state
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getApplyState() {
        return applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.apply_state
     *
     * @param applyState the value for tbl_apply.apply_state
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplyState(String applyState) {
        this.applyState = applyState == null ? null : applyState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.apply_date
     *
     * @return the value of tbl_apply.apply_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.apply_date
     *
     * @param applyDate the value for tbl_apply.apply_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.process_date
     *
     * @return the value of tbl_apply.process_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.process_date
     *
     * @param processDate the value for tbl_apply.process_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_apply.approver_id
     *
     * @return the value of tbl_apply.approver_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getApproverId() {
        return approverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_apply.approver_id
     *
     * @param approverId the value for tbl_apply.approver_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApproverId(String approverId) {
        this.approverId = approverId == null ? null : approverId.trim();
    }
}