package com.example.attendance.entity;

import java.util.Date;

import lombok.Data;

@Data
public class DateState {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.daily_id
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Long dailyId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.monthly_id
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Long monthlyId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.target_date
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Date targetDate;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private String workState;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_starttime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Date workStarttime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_endtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Date workEndtime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_overtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Integer workOvertime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_actualtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Integer workActualtime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_breaktime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Integer workBreaktime;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_start_location
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Object workStartLocation;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.work_end_location
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Object workEndLocation;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.date_apply_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private String dateApplyState;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.date_apply_date
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private Date dateApplyDate;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_date_state.edit_reason
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	private String editReason;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.daily_id
	 *
	 * @return the value of tbl_date_state.daily_id
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Long getDailyId() {
		return dailyId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.daily_id
	 *
	 * @param dailyId the value for tbl_date_state.daily_id
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setDailyId(Long dailyId) {
		this.dailyId = dailyId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.monthly_id
	 *
	 * @return the value of tbl_date_state.monthly_id
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Long getMonthlyId() {
		return monthlyId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.monthly_id
	 *
	 * @param monthlyId the value for tbl_date_state.monthly_id
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setMonthlyId(Long monthlyId) {
		this.monthlyId = monthlyId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.target_date
	 *
	 * @return the value of tbl_date_state.target_date
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Date getTargetDate() {
		return targetDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.target_date
	 *
	 * @param targetDate the value for tbl_date_state.target_date
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setTargetDate(Date targetDate) {
		this.targetDate = targetDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_state
	 *
	 * @return the value of tbl_date_state.work_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public String getWorkState() {
		return workState;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_state
	 *
	 * @param workState the value for tbl_date_state.work_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkState(String workState) {
		this.workState = workState == null ? null : workState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_starttime
	 *
	 * @return the value of tbl_date_state.work_starttime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Date getWorkStarttime() {
		return workStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_starttime
	 *
	 * @param workStarttime the value for tbl_date_state.work_starttime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkStarttime(Date workStarttime) {
		this.workStarttime = workStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_endtime
	 *
	 * @return the value of tbl_date_state.work_endtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Date getWorkEndtime() {
		return workEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_endtime
	 *
	 * @param workEndtime the value for tbl_date_state.work_endtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkEndtime(Date workEndtime) {
		this.workEndtime = workEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_overtime
	 *
	 * @return the value of tbl_date_state.work_overtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Integer getWorkOvertime() {
		return workOvertime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_overtime
	 *
	 * @param workOvertime the value for tbl_date_state.work_overtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkOvertime(Integer workOvertime) {
		this.workOvertime = workOvertime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_actualtime
	 *
	 * @return the value of tbl_date_state.work_actualtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Integer getWorkActualtime() {
		return workActualtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_actualtime
	 *
	 * @param workActualtime the value for tbl_date_state.work_actualtime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkActualtime(Integer workActualtime) {
		this.workActualtime = workActualtime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_breaktime
	 *
	 * @return the value of tbl_date_state.work_breaktime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Integer getWorkBreaktime() {
		return workBreaktime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_breaktime
	 *
	 * @param workBreaktime the value for tbl_date_state.work_breaktime
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkBreaktime(Integer workBreaktime) {
		this.workBreaktime = workBreaktime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_start_location
	 *
	 * @return the value of tbl_date_state.work_start_location
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Object getWorkStartLocation() {
		return workStartLocation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_start_location
	 *
	 * @param work_start_location the value for tbl_date_state.work_start_location
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkStartLocation(Object workStartLocation) {
		this.workStartLocation = workStartLocation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.work_end_location
	 *
	 * @return the value of tbl_date_state.work_end_location
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Object getWorkEndLocation() {
		return workEndLocation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.work_end_location
	 *
	 * @param work_end_location the value for tbl_date_state.work_end_location
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setWorkEndLocation(Object workEndLocation) {
		this.workEndLocation = workEndLocation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.date_apply_state
	 *
	 * @return the value of tbl_date_state.date_apply_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public String getDateApplyState() {
		return dateApplyState;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.date_apply_state
	 *
	 * @param dateApplyState the value for tbl_date_state.date_apply_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setDateApplyState(String dateApplyState) {
		this.dateApplyState = dateApplyState == null ? null : dateApplyState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.date_apply_date
	 *
	 * @return the value of tbl_date_state.date_apply_date
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Date getDateApplyDate() {
		return dateApplyDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.date_apply_date
	 *
	 * @param dateApplyDate the value for tbl_date_state.date_apply_date
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setDateApplyDate(Date dateApplyDate) {
		this.dateApplyDate = dateApplyDate;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_date_state.edit_reason
	 *
	 * @return the value of tbl_date_state.edit_reason
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public String getEditReason() {
		return editReason;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_date_state.edit_reason
	 *
	 * @param dateApplyState the value for tbl_date_state.edit_reason
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setEditReason(String editReason) {
		this.editReason = editReason == null ? null : editReason.trim();
	}
}