package com.example.attendance.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DateStateExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public DateStateExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value.getTime()), property);
		}

		protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Time> timeList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				timeList.add(new java.sql.Time(iter.next().getTime()));
			}
			addCriterion(condition, timeList, property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
		}

		public Criteria andDailyIdIsNull() {
			addCriterion("daily_id is null");
			return (Criteria) this;
		}

		public Criteria andDailyIdIsNotNull() {
			addCriterion("daily_id is not null");
			return (Criteria) this;
		}

		public Criteria andDailyIdEqualTo(Long value) {
			addCriterion("daily_id =", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotEqualTo(Long value) {
			addCriterion("daily_id <>", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdGreaterThan(Long value) {
			addCriterion("daily_id >", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("daily_id >=", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdLessThan(Long value) {
			addCriterion("daily_id <", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdLessThanOrEqualTo(Long value) {
			addCriterion("daily_id <=", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdIn(List<Long> values) {
			addCriterion("daily_id in", values, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotIn(List<Long> values) {
			addCriterion("daily_id not in", values, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdBetween(Long value1, Long value2) {
			addCriterion("daily_id between", value1, value2, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotBetween(Long value1, Long value2) {
			addCriterion("daily_id not between", value1, value2, "dailyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdIsNull() {
			addCriterion("monthly_id is null");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdIsNotNull() {
			addCriterion("monthly_id is not null");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdEqualTo(Long value) {
			addCriterion("monthly_id =", value, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdNotEqualTo(Long value) {
			addCriterion("monthly_id <>", value, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdGreaterThan(Long value) {
			addCriterion("monthly_id >", value, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("monthly_id >=", value, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdLessThan(Long value) {
			addCriterion("monthly_id <", value, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdLessThanOrEqualTo(Long value) {
			addCriterion("monthly_id <=", value, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdIn(List<Long> values) {
			addCriterion("monthly_id in", values, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdNotIn(List<Long> values) {
			addCriterion("monthly_id not in", values, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdBetween(Long value1, Long value2) {
			addCriterion("monthly_id between", value1, value2, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andMonthlyIdNotBetween(Long value1, Long value2) {
			addCriterion("monthly_id not between", value1, value2, "monthlyId");
			return (Criteria) this;
		}

		public Criteria andTargetDateIsNull() {
			addCriterion("target_date is null");
			return (Criteria) this;
		}

		public Criteria andTargetDateIsNotNull() {
			addCriterion("target_date is not null");
			return (Criteria) this;
		}

		public Criteria andTargetDateEqualTo(Date value) {
			addCriterionForJDBCDate("target_date =", value, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("target_date <>", value, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateGreaterThan(Date value) {
			addCriterionForJDBCDate("target_date >", value, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("target_date >=", value, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateLessThan(Date value) {
			addCriterionForJDBCDate("target_date <", value, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("target_date <=", value, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateIn(List<Date> values) {
			addCriterionForJDBCDate("target_date in", values, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("target_date not in", values, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("target_date between", value1, value2, "targetDate");
			return (Criteria) this;
		}

		public Criteria andTargetDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("target_date not between", value1, value2, "targetDate");
			return (Criteria) this;
		}

		public Criteria andWorkStateIsNull() {
			addCriterion("work_state is null");
			return (Criteria) this;
		}

		public Criteria andWorkStateIsNotNull() {
			addCriterion("work_state is not null");
			return (Criteria) this;
		}

		public Criteria andWorkStateEqualTo(String value) {
			addCriterion("work_state =", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateNotEqualTo(String value) {
			addCriterion("work_state <>", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateGreaterThan(String value) {
			addCriterion("work_state >", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateGreaterThanOrEqualTo(String value) {
			addCriterion("work_state >=", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateLessThan(String value) {
			addCriterion("work_state <", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateLessThanOrEqualTo(String value) {
			addCriterion("work_state <=", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateLike(String value) {
			addCriterion("work_state like", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateNotLike(String value) {
			addCriterion("work_state not like", value, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateIn(List<String> values) {
			addCriterion("work_state in", values, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateNotIn(List<String> values) {
			addCriterion("work_state not in", values, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateBetween(String value1, String value2) {
			addCriterion("work_state between", value1, value2, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStateNotBetween(String value1, String value2) {
			addCriterion("work_state not between", value1, value2, "workState");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeIsNull() {
			addCriterion("work_starttime is null");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeIsNotNull() {
			addCriterion("work_starttime is not null");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeEqualTo(Date value) {
			addCriterionForJDBCTime("work_starttime =", value, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeNotEqualTo(Date value) {
			addCriterionForJDBCTime("work_starttime <>", value, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeGreaterThan(Date value) {
			addCriterionForJDBCTime("work_starttime >", value, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("work_starttime >=", value, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeLessThan(Date value) {
			addCriterionForJDBCTime("work_starttime <", value, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("work_starttime <=", value, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeIn(List<Date> values) {
			addCriterionForJDBCTime("work_starttime in", values, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeNotIn(List<Date> values) {
			addCriterionForJDBCTime("work_starttime not in", values, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("work_starttime between", value1, value2, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkStarttimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("work_starttime not between", value1, value2, "workStarttime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeIsNull() {
			addCriterion("work_endtime is null");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeIsNotNull() {
			addCriterion("work_endtime is not null");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeEqualTo(Date value) {
			addCriterionForJDBCTime("work_endtime =", value, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeNotEqualTo(Date value) {
			addCriterionForJDBCTime("work_endtime <>", value, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeGreaterThan(Date value) {
			addCriterionForJDBCTime("work_endtime >", value, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("work_endtime >=", value, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeLessThan(Date value) {
			addCriterionForJDBCTime("work_endtime <", value, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("work_endtime <=", value, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeIn(List<Date> values) {
			addCriterionForJDBCTime("work_endtime in", values, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeNotIn(List<Date> values) {
			addCriterionForJDBCTime("work_endtime not in", values, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("work_endtime between", value1, value2, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkEndtimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("work_endtime not between", value1, value2, "workEndtime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeIsNull() {
			addCriterion("work_overtime is null");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeIsNotNull() {
			addCriterion("work_overtime is not null");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeEqualTo(Integer value) {
			addCriterion("work_overtime =", value, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeNotEqualTo(Integer value) {
			addCriterion("work_overtime <>", value, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeGreaterThan(Integer value) {
			addCriterion("work_overtime >", value, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("work_overtime >=", value, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeLessThan(Integer value) {
			addCriterion("work_overtime <", value, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeLessThanOrEqualTo(Integer value) {
			addCriterion("work_overtime <=", value, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeIn(List<Integer> values) {
			addCriterion("work_overtime in", values, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeNotIn(List<Integer> values) {
			addCriterion("work_overtime not in", values, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeBetween(Integer value1, Integer value2) {
			addCriterion("work_overtime between", value1, value2, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkOvertimeNotBetween(Integer value1, Integer value2) {
			addCriterion("work_overtime not between", value1, value2, "workOvertime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeIsNull() {
			addCriterion("work_actualtime is null");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeIsNotNull() {
			addCriterion("work_actualtime is not null");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeEqualTo(Integer value) {
			addCriterion("work_actualtime =", value, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeNotEqualTo(Integer value) {
			addCriterion("work_actualtime <>", value, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeGreaterThan(Integer value) {
			addCriterion("work_actualtime >", value, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("work_actualtime >=", value, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeLessThan(Integer value) {
			addCriterion("work_actualtime <", value, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeLessThanOrEqualTo(Integer value) {
			addCriterion("work_actualtime <=", value, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeIn(List<Integer> values) {
			addCriterion("work_actualtime in", values, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeNotIn(List<Integer> values) {
			addCriterion("work_actualtime not in", values, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeBetween(Integer value1, Integer value2) {
			addCriterion("work_actualtime between", value1, value2, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkActualtimeNotBetween(Integer value1, Integer value2) {
			addCriterion("work_actualtime not between", value1, value2, "workActualtime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeIsNull() {
			addCriterion("work_breaktime is null");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeIsNotNull() {
			addCriterion("work_breaktime is not null");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeEqualTo(Integer value) {
			addCriterion("work_breaktime =", value, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeNotEqualTo(Integer value) {
			addCriterion("work_breaktime <>", value, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeGreaterThan(Integer value) {
			addCriterion("work_breaktime >", value, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("work_breaktime >=", value, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeLessThan(Integer value) {
			addCriterion("work_breaktime <", value, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeLessThanOrEqualTo(Integer value) {
			addCriterion("work_breaktime <=", value, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeIn(List<Integer> values) {
			addCriterion("work_breaktime in", values, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeNotIn(List<Integer> values) {
			addCriterion("work_breaktime not in", values, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeBetween(Integer value1, Integer value2) {
			addCriterion("work_breaktime between", value1, value2, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkBreaktimeNotBetween(Integer value1, Integer value2) {
			addCriterion("work_breaktime not between", value1, value2, "workBreaktime");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationIsNull() {
			addCriterion("work_start_location is null");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationIsNotNull() {
			addCriterion("work_start_location is not null");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationEqualTo(Object value) {
			addCriterion("work_start_location =", value, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationNotEqualTo(Object value) {
			addCriterion("work_start_location <>", value, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationGreaterThan(Object value) {
			addCriterion("work_start_location >", value, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationGreaterThanOrEqualTo(Object value) {
			addCriterion("work_start_location >=", value, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationLessThan(Object value) {
			addCriterion("work_start_location <", value, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationLessThanOrEqualTo(Object value) {
			addCriterion("work_start_location <=", value, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationIn(List<Object> values) {
			addCriterion("work_start_location in", values, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationNotIn(List<Object> values) {
			addCriterion("work_start_location not in", values, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationBetween(Object value1, Object value2) {
			addCriterion("work_start_location between", value1, value2, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkStartLocationNotBetween(Object value1, Object value2) {
			addCriterion("work_start_location not between", value1, value2, "workStartLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationIsNull() {
			addCriterion("work_end_location is null");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationIsNotNull() {
			addCriterion("work_end_location is not null");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationEqualTo(Object value) {
			addCriterion("work_end_location =", value, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationNotEqualTo(Object value) {
			addCriterion("work_end_location <>", value, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationGreaterThan(Object value) {
			addCriterion("work_end_location >", value, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationGreaterThanOrEqualTo(Object value) {
			addCriterion("work_end_location >=", value, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationLessThan(Object value) {
			addCriterion("work_end_location <", value, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationLessThanOrEqualTo(Object value) {
			addCriterion("work_end_location <=", value, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationIn(List<Object> values) {
			addCriterion("work_end_location in", values, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationNotIn(List<Object> values) {
			addCriterion("work_end_location not in", values, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationBetween(Object value1, Object value2) {
			addCriterion("work_end_location between", value1, value2, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andWorkEndLocationNotBetween(Object value1, Object value2) {
			addCriterion("work_end_location not between", value1, value2, "workEndLocation");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateIsNull() {
			addCriterion("date_apply_state is null");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateIsNotNull() {
			addCriterion("date_apply_state is not null");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateEqualTo(String value) {
			addCriterion("date_apply_state =", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateNotEqualTo(String value) {
			addCriterion("date_apply_state <>", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateGreaterThan(String value) {
			addCriterion("date_apply_state >", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateGreaterThanOrEqualTo(String value) {
			addCriterion("date_apply_state >=", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateLessThan(String value) {
			addCriterion("date_apply_state <", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateLessThanOrEqualTo(String value) {
			addCriterion("date_apply_state <=", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateLike(String value) {
			addCriterion("date_apply_state like", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateNotLike(String value) {
			addCriterion("date_apply_state not like", value, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateIn(List<String> values) {
			addCriterion("date_apply_state in", values, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateNotIn(List<String> values) {
			addCriterion("date_apply_state not in", values, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateBetween(String value1, String value2) {
			addCriterion("date_apply_state between", value1, value2, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyStateNotBetween(String value1, String value2) {
			addCriterion("date_apply_state not between", value1, value2, "dateApplyState");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateIsNull() {
			addCriterion("date_apply_date is null");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateIsNotNull() {
			addCriterion("date_apply_date is not null");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateEqualTo(Date value) {
			addCriterion("date_apply_date =", value, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateNotEqualTo(Date value) {
			addCriterion("date_apply_date <>", value, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateGreaterThan(Date value) {
			addCriterion("date_apply_date >", value, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateGreaterThanOrEqualTo(Date value) {
			addCriterion("date_apply_date >=", value, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateLessThan(Date value) {
			addCriterion("date_apply_date <", value, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateLessThanOrEqualTo(Date value) {
			addCriterion("date_apply_date <=", value, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateIn(List<Date> values) {
			addCriterion("date_apply_date in", values, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateNotIn(List<Date> values) {
			addCriterion("date_apply_date not in", values, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateBetween(Date value1, Date value2) {
			addCriterion("date_apply_date between", value1, value2, "dateApplyDate");
			return (Criteria) this;
		}

		public Criteria andDateApplyDateNotBetween(Date value1, Date value2) {
			addCriterion("date_apply_date not between", value1, value2, "dateApplyDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated do_not_delete_during_merge Mon Aug 17 20:46:17 JST 2026
	 */
	public static class Criteria extends GeneratedCriteria {
		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}