package com.example.attendance.entity;

import java.util.Date;

public class Holiday {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_holiday.holiday_date
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    private Date holidayDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_holiday.holiday_name
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    private String holidayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_holiday.source_type
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    private String sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_holiday.updated_at
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_holiday.holiday_date
     *
     * @return the value of mst_holiday.holiday_date
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public Date getHolidayDate() {
        return holidayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_holiday.holiday_date
     *
     * @param holidayDate the value for mst_holiday.holiday_date
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public void setHolidayDate(Date holidayDate) {
        this.holidayDate = holidayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_holiday.holiday_name
     *
     * @return the value of mst_holiday.holiday_name
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public String getHolidayName() {
        return holidayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_holiday.holiday_name
     *
     * @param holidayName the value for mst_holiday.holiday_name
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public void setHolidayName(String holidayName) {
        this.holidayName = holidayName == null ? null : holidayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_holiday.source_type
     *
     * @return the value of mst_holiday.source_type
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_holiday.source_type
     *
     * @param sourceType the value for mst_holiday.source_type
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType == null ? null : sourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_holiday.updated_at
     *
     * @return the value of mst_holiday.updated_at
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_holiday.updated_at
     *
     * @param updatedAt the value for mst_holiday.updated_at
     *
     * @mbg.generated Thu Sep 17 11:00:45 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}