package com.example.attendance.entity;

import java.math.BigDecimal;
import java.util.Date;

import lombok.Data;

@Data
public class MonthState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.monthly_id
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private Long monthlyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.user_id
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.target_year
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private Short targetYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.target_month
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private Short targetMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.work_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private BigDecimal workDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.holiday_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private BigDecimal holidayDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.absent_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private BigDecimal absentDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.month_overtime
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private Integer monthOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.month_actualtime
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private Integer monthActualtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.month_apply_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private String monthApplyState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_state.month_apply_date
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    private Date monthApplyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.monthly_id
     *
     * @return the value of tbl_month_state.monthly_id
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Long getMonthlyId() {
        return monthlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.monthly_id
     *
     * @param monthlyId the value for tbl_month_state.monthly_id
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setMonthlyId(Long monthlyId) {
        this.monthlyId = monthlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.user_id
     *
     * @return the value of tbl_month_state.user_id
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.user_id
     *
     * @param userId the value for tbl_month_state.user_id
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.target_year
     *
     * @return the value of tbl_month_state.target_year
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Short getTargetYear() {
        return targetYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.target_year
     *
     * @param targetYear the value for tbl_month_state.target_year
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setTargetYear(Short targetYear) {
        this.targetYear = targetYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.target_month
     *
     * @return the value of tbl_month_state.target_month
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Short getTargetMonth() {
        return targetMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.target_month
     *
     * @param targetMonth the value for tbl_month_state.target_month
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setTargetMonth(Short targetMonth) {
        this.targetMonth = targetMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.work_days
     *
     * @return the value of tbl_month_state.work_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public BigDecimal getWorkDays() {
        return workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.work_days
     *
     * @param workDays the value for tbl_month_state.work_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setWorkDays(BigDecimal workDays) {
        this.workDays = workDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.holiday_days
     *
     * @return the value of tbl_month_state.holiday_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public BigDecimal getHolidayDays() {
        return holidayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.holiday_days
     *
     * @param holidayDays the value for tbl_month_state.holiday_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setHolidayDays(BigDecimal holidayDays) {
        this.holidayDays = holidayDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.absent_days
     *
     * @return the value of tbl_month_state.absent_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public BigDecimal getAbsentDays() {
        return absentDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.absent_days
     *
     * @param absentDays the value for tbl_month_state.absent_days
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setAbsentDays(BigDecimal absentDays) {
        this.absentDays = absentDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.month_overtime
     *
     * @return the value of tbl_month_state.month_overtime
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Integer getMonthOvertime() {
        return monthOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.month_overtime
     *
     * @param monthOvertime the value for tbl_month_state.month_overtime
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setMonthOvertime(Integer monthOvertime) {
        this.monthOvertime = monthOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.month_actualtime
     *
     * @return the value of tbl_month_state.month_actualtime
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Integer getMonthActualtime() {
        return monthActualtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.month_actualtime
     *
     * @param monthActualtime the value for tbl_month_state.month_actualtime
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setMonthActualtime(Integer monthActualtime) {
        this.monthActualtime = monthActualtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.month_apply_state
     *
     * @return the value of tbl_month_state.month_apply_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public String getMonthApplyState() {
        return monthApplyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.month_apply_state
     *
     * @param monthApplyState the value for tbl_month_state.month_apply_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setMonthApplyState(String monthApplyState) {
        this.monthApplyState = monthApplyState == null ? null : monthApplyState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_state.month_apply_date
     *
     * @return the value of tbl_month_state.month_apply_date
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Date getMonthApplyDate() {
        return monthApplyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_state.month_apply_date
     *
     * @param monthApplyDate the value for tbl_month_state.month_apply_date
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setMonthApplyDate(Date monthApplyDate) {
        this.monthApplyDate = monthApplyDate;
    }
}