package com.example.attendance.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MonthStateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public MonthStateExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMonthlyIdIsNull() {
            addCriterion("monthly_id is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdIsNotNull() {
            addCriterion("monthly_id is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdEqualTo(Long value) {
            addCriterion("monthly_id =", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdNotEqualTo(Long value) {
            addCriterion("monthly_id <>", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdGreaterThan(Long value) {
            addCriterion("monthly_id >", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("monthly_id >=", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdLessThan(Long value) {
            addCriterion("monthly_id <", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdLessThanOrEqualTo(Long value) {
            addCriterion("monthly_id <=", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdIn(List<Long> values) {
            addCriterion("monthly_id in", values, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdNotIn(List<Long> values) {
            addCriterion("monthly_id not in", values, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdBetween(Long value1, Long value2) {
            addCriterion("monthly_id between", value1, value2, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdNotBetween(Long value1, Long value2) {
            addCriterion("monthly_id not between", value1, value2, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andTargetYearIsNull() {
            addCriterion("target_year is null");
            return (Criteria) this;
        }

        public Criteria andTargetYearIsNotNull() {
            addCriterion("target_year is not null");
            return (Criteria) this;
        }

        public Criteria andTargetYearEqualTo(Short value) {
            addCriterion("target_year =", value, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearNotEqualTo(Short value) {
            addCriterion("target_year <>", value, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearGreaterThan(Short value) {
            addCriterion("target_year >", value, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearGreaterThanOrEqualTo(Short value) {
            addCriterion("target_year >=", value, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearLessThan(Short value) {
            addCriterion("target_year <", value, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearLessThanOrEqualTo(Short value) {
            addCriterion("target_year <=", value, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearIn(List<Short> values) {
            addCriterion("target_year in", values, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearNotIn(List<Short> values) {
            addCriterion("target_year not in", values, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearBetween(Short value1, Short value2) {
            addCriterion("target_year between", value1, value2, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetYearNotBetween(Short value1, Short value2) {
            addCriterion("target_year not between", value1, value2, "targetYear");
            return (Criteria) this;
        }

        public Criteria andTargetMonthIsNull() {
            addCriterion("target_month is null");
            return (Criteria) this;
        }

        public Criteria andTargetMonthIsNotNull() {
            addCriterion("target_month is not null");
            return (Criteria) this;
        }

        public Criteria andTargetMonthEqualTo(Short value) {
            addCriterion("target_month =", value, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthNotEqualTo(Short value) {
            addCriterion("target_month <>", value, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthGreaterThan(Short value) {
            addCriterion("target_month >", value, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthGreaterThanOrEqualTo(Short value) {
            addCriterion("target_month >=", value, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthLessThan(Short value) {
            addCriterion("target_month <", value, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthLessThanOrEqualTo(Short value) {
            addCriterion("target_month <=", value, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthIn(List<Short> values) {
            addCriterion("target_month in", values, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthNotIn(List<Short> values) {
            addCriterion("target_month not in", values, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthBetween(Short value1, Short value2) {
            addCriterion("target_month between", value1, value2, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andTargetMonthNotBetween(Short value1, Short value2) {
            addCriterion("target_month not between", value1, value2, "targetMonth");
            return (Criteria) this;
        }

        public Criteria andWorkDaysIsNull() {
            addCriterion("work_days is null");
            return (Criteria) this;
        }

        public Criteria andWorkDaysIsNotNull() {
            addCriterion("work_days is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDaysEqualTo(BigDecimal value) {
            addCriterion("work_days =", value, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysNotEqualTo(BigDecimal value) {
            addCriterion("work_days <>", value, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysGreaterThan(BigDecimal value) {
            addCriterion("work_days >", value, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("work_days >=", value, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysLessThan(BigDecimal value) {
            addCriterion("work_days <", value, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysLessThanOrEqualTo(BigDecimal value) {
            addCriterion("work_days <=", value, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysIn(List<BigDecimal> values) {
            addCriterion("work_days in", values, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysNotIn(List<BigDecimal> values) {
            addCriterion("work_days not in", values, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("work_days between", value1, value2, "workDays");
            return (Criteria) this;
        }

        public Criteria andWorkDaysNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("work_days not between", value1, value2, "workDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysIsNull() {
            addCriterion("holiday_days is null");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysIsNotNull() {
            addCriterion("holiday_days is not null");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysEqualTo(BigDecimal value) {
            addCriterion("holiday_days =", value, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysNotEqualTo(BigDecimal value) {
            addCriterion("holiday_days <>", value, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysGreaterThan(BigDecimal value) {
            addCriterion("holiday_days >", value, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("holiday_days >=", value, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysLessThan(BigDecimal value) {
            addCriterion("holiday_days <", value, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysLessThanOrEqualTo(BigDecimal value) {
            addCriterion("holiday_days <=", value, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysIn(List<BigDecimal> values) {
            addCriterion("holiday_days in", values, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysNotIn(List<BigDecimal> values) {
            addCriterion("holiday_days not in", values, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("holiday_days between", value1, value2, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andHolidayDaysNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("holiday_days not between", value1, value2, "holidayDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysIsNull() {
            addCriterion("absent_days is null");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysIsNotNull() {
            addCriterion("absent_days is not null");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysEqualTo(BigDecimal value) {
            addCriterion("absent_days =", value, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysNotEqualTo(BigDecimal value) {
            addCriterion("absent_days <>", value, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysGreaterThan(BigDecimal value) {
            addCriterion("absent_days >", value, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("absent_days >=", value, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysLessThan(BigDecimal value) {
            addCriterion("absent_days <", value, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysLessThanOrEqualTo(BigDecimal value) {
            addCriterion("absent_days <=", value, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysIn(List<BigDecimal> values) {
            addCriterion("absent_days in", values, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysNotIn(List<BigDecimal> values) {
            addCriterion("absent_days not in", values, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("absent_days between", value1, value2, "absentDays");
            return (Criteria) this;
        }

        public Criteria andAbsentDaysNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("absent_days not between", value1, value2, "absentDays");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeIsNull() {
            addCriterion("month_overtime is null");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeIsNotNull() {
            addCriterion("month_overtime is not null");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeEqualTo(Integer value) {
            addCriterion("month_overtime =", value, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeNotEqualTo(Integer value) {
            addCriterion("month_overtime <>", value, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeGreaterThan(Integer value) {
            addCriterion("month_overtime >", value, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("month_overtime >=", value, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeLessThan(Integer value) {
            addCriterion("month_overtime <", value, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeLessThanOrEqualTo(Integer value) {
            addCriterion("month_overtime <=", value, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeIn(List<Integer> values) {
            addCriterion("month_overtime in", values, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeNotIn(List<Integer> values) {
            addCriterion("month_overtime not in", values, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeBetween(Integer value1, Integer value2) {
            addCriterion("month_overtime between", value1, value2, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthOvertimeNotBetween(Integer value1, Integer value2) {
            addCriterion("month_overtime not between", value1, value2, "monthOvertime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeIsNull() {
            addCriterion("month_actualtime is null");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeIsNotNull() {
            addCriterion("month_actualtime is not null");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeEqualTo(Integer value) {
            addCriterion("month_actualtime =", value, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeNotEqualTo(Integer value) {
            addCriterion("month_actualtime <>", value, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeGreaterThan(Integer value) {
            addCriterion("month_actualtime >", value, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("month_actualtime >=", value, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeLessThan(Integer value) {
            addCriterion("month_actualtime <", value, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeLessThanOrEqualTo(Integer value) {
            addCriterion("month_actualtime <=", value, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeIn(List<Integer> values) {
            addCriterion("month_actualtime in", values, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeNotIn(List<Integer> values) {
            addCriterion("month_actualtime not in", values, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeBetween(Integer value1, Integer value2) {
            addCriterion("month_actualtime between", value1, value2, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthActualtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("month_actualtime not between", value1, value2, "monthActualtime");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateIsNull() {
            addCriterion("month_apply_state is null");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateIsNotNull() {
            addCriterion("month_apply_state is not null");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateEqualTo(String value) {
            addCriterion("month_apply_state =", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateNotEqualTo(String value) {
            addCriterion("month_apply_state <>", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateGreaterThan(String value) {
            addCriterion("month_apply_state >", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateGreaterThanOrEqualTo(String value) {
            addCriterion("month_apply_state >=", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateLessThan(String value) {
            addCriterion("month_apply_state <", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateLessThanOrEqualTo(String value) {
            addCriterion("month_apply_state <=", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateLike(String value) {
            addCriterion("month_apply_state like", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateNotLike(String value) {
            addCriterion("month_apply_state not like", value, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateIn(List<String> values) {
            addCriterion("month_apply_state in", values, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateNotIn(List<String> values) {
            addCriterion("month_apply_state not in", values, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateBetween(String value1, String value2) {
            addCriterion("month_apply_state between", value1, value2, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyStateNotBetween(String value1, String value2) {
            addCriterion("month_apply_state not between", value1, value2, "monthApplyState");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateIsNull() {
            addCriterion("month_apply_date is null");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateIsNotNull() {
            addCriterion("month_apply_date is not null");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateEqualTo(Date value) {
            addCriterion("month_apply_date =", value, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateNotEqualTo(Date value) {
            addCriterion("month_apply_date <>", value, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateGreaterThan(Date value) {
            addCriterion("month_apply_date >", value, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("month_apply_date >=", value, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateLessThan(Date value) {
            addCriterion("month_apply_date <", value, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("month_apply_date <=", value, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateIn(List<Date> values) {
            addCriterion("month_apply_date in", values, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateNotIn(List<Date> values) {
            addCriterion("month_apply_date not in", values, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateBetween(Date value1, Date value2) {
            addCriterion("month_apply_date between", value1, value2, "monthApplyDate");
            return (Criteria) this;
        }

        public Criteria andMonthApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("month_apply_date not between", value1, value2, "monthApplyDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_month_state
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 17 20:46:17 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_month_state
     *
     * @mbg.generated Mon Aug 17 20:46:17 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}