package com.example.attendance.entity;

public class MonthApplyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_apply_detail.month_apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Long monthApplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_apply_detail.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Long applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_apply_detail.monthly_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Long monthlyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_month_apply_detail.approver_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String approverRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_apply_detail.month_apply_id
     *
     * @return the value of tbl_month_apply_detail.month_apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Long getMonthApplyId() {
        return monthApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_apply_detail.month_apply_id
     *
     * @param monthApplyId the value for tbl_month_apply_detail.month_apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setMonthApplyId(Long monthApplyId) {
        this.monthApplyId = monthApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_apply_detail.apply_id
     *
     * @return the value of tbl_month_apply_detail.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Long getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_apply_detail.apply_id
     *
     * @param applyId the value for tbl_month_apply_detail.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_apply_detail.monthly_id
     *
     * @return the value of tbl_month_apply_detail.monthly_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Long getMonthlyId() {
        return monthlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_apply_detail.monthly_id
     *
     * @param monthlyId the value for tbl_month_apply_detail.monthly_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setMonthlyId(Long monthlyId) {
        this.monthlyId = monthlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_month_apply_detail.approver_remark
     *
     * @return the value of tbl_month_apply_detail.approver_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getApproverRemark() {
        return approverRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_month_apply_detail.approver_remark
     *
     * @param approverRemark the value for tbl_month_apply_detail.approver_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApproverRemark(String approverRemark) {
        this.approverRemark = approverRemark == null ? null : approverRemark.trim();
    }
}