package com.example.attendance.entity;

import java.util.ArrayList;
import java.util.List;

public class MonthApplyDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public MonthApplyDetailExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMonthApplyIdIsNull() {
            addCriterion("month_apply_id is null");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdIsNotNull() {
            addCriterion("month_apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdEqualTo(Long value) {
            addCriterion("month_apply_id =", value, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdNotEqualTo(Long value) {
            addCriterion("month_apply_id <>", value, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdGreaterThan(Long value) {
            addCriterion("month_apply_id >", value, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("month_apply_id >=", value, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdLessThan(Long value) {
            addCriterion("month_apply_id <", value, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdLessThanOrEqualTo(Long value) {
            addCriterion("month_apply_id <=", value, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdIn(List<Long> values) {
            addCriterion("month_apply_id in", values, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdNotIn(List<Long> values) {
            addCriterion("month_apply_id not in", values, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdBetween(Long value1, Long value2) {
            addCriterion("month_apply_id between", value1, value2, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andMonthApplyIdNotBetween(Long value1, Long value2) {
            addCriterion("month_apply_id not between", value1, value2, "monthApplyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("apply_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(Long value) {
            addCriterion("apply_id =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(Long value) {
            addCriterion("apply_id <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(Long value) {
            addCriterion("apply_id >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("apply_id >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(Long value) {
            addCriterion("apply_id <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(Long value) {
            addCriterion("apply_id <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<Long> values) {
            addCriterion("apply_id in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<Long> values) {
            addCriterion("apply_id not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(Long value1, Long value2) {
            addCriterion("apply_id between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(Long value1, Long value2) {
            addCriterion("apply_id not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdIsNull() {
            addCriterion("monthly_id is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdIsNotNull() {
            addCriterion("monthly_id is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdEqualTo(Long value) {
            addCriterion("monthly_id =", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdNotEqualTo(Long value) {
            addCriterion("monthly_id <>", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdGreaterThan(Long value) {
            addCriterion("monthly_id >", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("monthly_id >=", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdLessThan(Long value) {
            addCriterion("monthly_id <", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdLessThanOrEqualTo(Long value) {
            addCriterion("monthly_id <=", value, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdIn(List<Long> values) {
            addCriterion("monthly_id in", values, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdNotIn(List<Long> values) {
            addCriterion("monthly_id not in", values, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdBetween(Long value1, Long value2) {
            addCriterion("monthly_id between", value1, value2, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andMonthlyIdNotBetween(Long value1, Long value2) {
            addCriterion("monthly_id not between", value1, value2, "monthlyId");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkIsNull() {
            addCriterion("approver_remark is null");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkIsNotNull() {
            addCriterion("approver_remark is not null");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkEqualTo(String value) {
            addCriterion("approver_remark =", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotEqualTo(String value) {
            addCriterion("approver_remark <>", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkGreaterThan(String value) {
            addCriterion("approver_remark >", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("approver_remark >=", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkLessThan(String value) {
            addCriterion("approver_remark <", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkLessThanOrEqualTo(String value) {
            addCriterion("approver_remark <=", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkLike(String value) {
            addCriterion("approver_remark like", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotLike(String value) {
            addCriterion("approver_remark not like", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkIn(List<String> values) {
            addCriterion("approver_remark in", values, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotIn(List<String> values) {
            addCriterion("approver_remark not in", values, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkBetween(String value1, String value2) {
            addCriterion("approver_remark between", value1, value2, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotBetween(String value1, String value2) {
            addCriterion("approver_remark not between", value1, value2, "approverRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 07 22:48:55 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_month_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}