package com.example.attendance.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class UserInfoExample {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public UserInfoExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserKanaIsNull() {
			addCriterion("user_kana is null");
			return (Criteria) this;
		}

		public Criteria andUserKanaIsNotNull() {
			addCriterion("user_kana is not null");
			return (Criteria) this;
		}

		public Criteria andUserKanaEqualTo(String value) {
			addCriterion("user_kana =", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaNotEqualTo(String value) {
			addCriterion("user_kana <>", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaGreaterThan(String value) {
			addCriterion("user_kana >", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaGreaterThanOrEqualTo(String value) {
			addCriterion("user_kana >=", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaLessThan(String value) {
			addCriterion("user_kana <", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaLessThanOrEqualTo(String value) {
			addCriterion("user_kana <=", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaLike(String value) {
			addCriterion("user_kana like", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaNotLike(String value) {
			addCriterion("user_kana not like", value, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaIn(List<String> values) {
			addCriterion("user_kana in", values, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaNotIn(List<String> values) {
			addCriterion("user_kana not in", values, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaBetween(String value1, String value2) {
			addCriterion("user_kana between", value1, value2, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserKanaNotBetween(String value1, String value2) {
			addCriterion("user_kana not between", value1, value2, "userKana");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityIsNull() {
			addCriterion("user_authority is null");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityIsNotNull() {
			addCriterion("user_authority is not null");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityEqualTo(String value) {
			addCriterion("user_authority =", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityNotEqualTo(String value) {
			addCriterion("user_authority <>", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityGreaterThan(String value) {
			addCriterion("user_authority >", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityGreaterThanOrEqualTo(String value) {
			addCriterion("user_authority >=", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityLessThan(String value) {
			addCriterion("user_authority <", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityLessThanOrEqualTo(String value) {
			addCriterion("user_authority <=", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityLike(String value) {
			addCriterion("user_authority like", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityNotLike(String value) {
			addCriterion("user_authority not like", value, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityIn(List<String> values) {
			addCriterion("user_authority in", values, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityNotIn(List<String> values) {
			addCriterion("user_authority not in", values, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityBetween(String value1, String value2) {
			addCriterion("user_authority between", value1, value2, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserAuthorityNotBetween(String value1, String value2) {
			addCriterion("user_authority not between", value1, value2, "userAuthority");
			return (Criteria) this;
		}

		public Criteria andUserEmailIsNull() {
			addCriterion("user_email is null");
			return (Criteria) this;
		}

		public Criteria andUserEmailIsNotNull() {
			addCriterion("user_email is not null");
			return (Criteria) this;
		}

		public Criteria andUserEmailEqualTo(String value) {
			addCriterion("user_email =", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotEqualTo(String value) {
			addCriterion("user_email <>", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailGreaterThan(String value) {
			addCriterion("user_email >", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
			addCriterion("user_email >=", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLessThan(String value) {
			addCriterion("user_email <", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLessThanOrEqualTo(String value) {
			addCriterion("user_email <=", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailLike(String value) {
			addCriterion("user_email like", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotLike(String value) {
			addCriterion("user_email not like", value, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailIn(List<String> values) {
			addCriterion("user_email in", values, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotIn(List<String> values) {
			addCriterion("user_email not in", values, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailBetween(String value1, String value2) {
			addCriterion("user_email between", value1, value2, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserEmailNotBetween(String value1, String value2) {
			addCriterion("user_email not between", value1, value2, "userEmail");
			return (Criteria) this;
		}

		public Criteria andUserPassIsNull() {
			addCriterion("user_pass is null");
			return (Criteria) this;
		}

		public Criteria andUserPassIsNotNull() {
			addCriterion("user_pass is not null");
			return (Criteria) this;
		}

		public Criteria andUserPassEqualTo(String value) {
			addCriterion("user_pass =", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassNotEqualTo(String value) {
			addCriterion("user_pass <>", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassGreaterThan(String value) {
			addCriterion("user_pass >", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassGreaterThanOrEqualTo(String value) {
			addCriterion("user_pass >=", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassLessThan(String value) {
			addCriterion("user_pass <", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassLessThanOrEqualTo(String value) {
			addCriterion("user_pass <=", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassLike(String value) {
			addCriterion("user_pass like", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassNotLike(String value) {
			addCriterion("user_pass not like", value, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassIn(List<String> values) {
			addCriterion("user_pass in", values, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassNotIn(List<String> values) {
			addCriterion("user_pass not in", values, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassBetween(String value1, String value2) {
			addCriterion("user_pass between", value1, value2, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserPassNotBetween(String value1, String value2) {
			addCriterion("user_pass not between", value1, value2, "userPass");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentIsNull() {
			addCriterion("user_department is null");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentIsNotNull() {
			addCriterion("user_department is not null");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentEqualTo(String value) {
			addCriterion("user_department =", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentNotEqualTo(String value) {
			addCriterion("user_department <>", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentGreaterThan(String value) {
			addCriterion("user_department >", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentGreaterThanOrEqualTo(String value) {
			addCriterion("user_department >=", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentLessThan(String value) {
			addCriterion("user_department <", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentLessThanOrEqualTo(String value) {
			addCriterion("user_department <=", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentLike(String value) {
			addCriterion("user_department like", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentNotLike(String value) {
			addCriterion("user_department not like", value, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentIn(List<String> values) {
			addCriterion("user_department in", values, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentNotIn(List<String> values) {
			addCriterion("user_department not in", values, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentBetween(String value1, String value2) {
			addCriterion("user_department between", value1, value2, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andUserDepartmentNotBetween(String value1, String value2) {
			addCriterion("user_department not between", value1, value2, "userDepartment");
			return (Criteria) this;
		}

		public Criteria andApproverIdIsNull() {
			addCriterion("approver_id is null");
			return (Criteria) this;
		}

		public Criteria andApproverIdIsNotNull() {
			addCriterion("approver_id is not null");
			return (Criteria) this;
		}

		public Criteria andApproverIdEqualTo(String value) {
			addCriterion("approver_id =", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdNotEqualTo(String value) {
			addCriterion("approver_id <>", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdGreaterThan(String value) {
			addCriterion("approver_id >", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdGreaterThanOrEqualTo(String value) {
			addCriterion("approver_id >=", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdLessThan(String value) {
			addCriterion("approver_id <", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdLessThanOrEqualTo(String value) {
			addCriterion("approver_id <=", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdLike(String value) {
			addCriterion("approver_id like", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdNotLike(String value) {
			addCriterion("approver_id not like", value, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdIn(List<String> values) {
			addCriterion("approver_id in", values, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdNotIn(List<String> values) {
			addCriterion("approver_id not in", values, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdBetween(String value1, String value2) {
			addCriterion("approver_id between", value1, value2, "approverId");
			return (Criteria) this;
		}

		public Criteria andApproverIdNotBetween(String value1, String value2) {
			addCriterion("approver_id not between", value1, value2, "approverId");
			return (Criteria) this;
		}

		public Criteria andPaidVacationIsNull() {
			addCriterion("paid_vacation is null");
			return (Criteria) this;
		}

		public Criteria andPaidVacationIsNotNull() {
			addCriterion("paid_vacation is not null");
			return (Criteria) this;
		}

		public Criteria andPaidVacationEqualTo(BigDecimal value) {
			addCriterion("paid_vacation =", value, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationNotEqualTo(BigDecimal value) {
			addCriterion("paid_vacation <>", value, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationGreaterThan(BigDecimal value) {
			addCriterion("paid_vacation >", value, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("paid_vacation >=", value, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationLessThan(BigDecimal value) {
			addCriterion("paid_vacation <", value, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationLessThanOrEqualTo(BigDecimal value) {
			addCriterion("paid_vacation <=", value, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationIn(List<BigDecimal> values) {
			addCriterion("paid_vacation in", values, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationNotIn(List<BigDecimal> values) {
			addCriterion("paid_vacation not in", values, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("paid_vacation between", value1, value2, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andPaidVacationNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("paid_vacation not between", value1, value2, "paidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationIsNull() {
			addCriterion("rest_paid_vacation is null");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationIsNotNull() {
			addCriterion("rest_paid_vacation is not null");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationEqualTo(BigDecimal value) {
			addCriterion("rest_paid_vacation =", value, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationNotEqualTo(BigDecimal value) {
			addCriterion("rest_paid_vacation <>", value, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationGreaterThan(BigDecimal value) {
			addCriterion("rest_paid_vacation >", value, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("rest_paid_vacation >=", value, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationLessThan(BigDecimal value) {
			addCriterion("rest_paid_vacation <", value, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationLessThanOrEqualTo(BigDecimal value) {
			addCriterion("rest_paid_vacation <=", value, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationIn(List<BigDecimal> values) {
			addCriterion("rest_paid_vacation in", values, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationNotIn(List<BigDecimal> values) {
			addCriterion("rest_paid_vacation not in", values, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("rest_paid_vacation between", value1, value2, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andRestPaidVacationNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("rest_paid_vacation not between", value1, value2, "restPaidVacation");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(String value) {
			addCriterion("delete_flg =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(String value) {
			addCriterion("delete_flg <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(String value) {
			addCriterion("delete_flg >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
			addCriterion("delete_flg >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(String value) {
			addCriterion("delete_flg <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
			addCriterion("delete_flg <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLike(String value) {
			addCriterion("delete_flg like", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotLike(String value) {
			addCriterion("delete_flg not like", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<String> values) {
			addCriterion("delete_flg in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<String> values) {
			addCriterion("delete_flg not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(String value1, String value2) {
			addCriterion("delete_flg between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(String value1, String value2) {
			addCriterion("delete_flg not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated do_not_delete_during_merge Fri Aug 14 15:55:23 JST 2026
	 */
	public static class Criteria extends GeneratedCriteria {
		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}