package com.example.attendance.entity;

import java.math.BigDecimal;

import lombok.Data;

@Data
public class UserInfo {
	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_id
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_name
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userName;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_kana
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userKana;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_authority
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userAuthority;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_email
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userEmail;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_pass
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userPass;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.user_department
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String userDepartment;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.approver_id
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String approverId;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.paid_vacation
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private BigDecimal paidVacation;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.rest_paid_vacation
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private BigDecimal restPaidVacation;

	/**
	 *
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_user_info.delete_flg
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	private String deleteFlg;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_id
	 *
	 * @return the value of tbl_user_info.user_id
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_id
	 *
	 * @param userId the value for tbl_user_info.user_id
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_name
	 *
	 * @return the value of tbl_user_info.user_name
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_name
	 *
	 * @param userName the value for tbl_user_info.user_name
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_kana
	 *
	 * @return the value of tbl_user_info.user_kana
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserKana() {
		return userKana;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_kana
	 *
	 * @param userKana the value for tbl_user_info.user_kana
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserKana(String userKana) {
		this.userKana = userKana == null ? null : userKana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_authority
	 *
	 * @return the value of tbl_user_info.user_authority
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserAuthority() {
		return userAuthority;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_authority
	 *
	 * @param userAuthority the value for tbl_user_info.user_authority
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserAuthority(String userAuthority) {
		this.userAuthority = userAuthority == null ? null : userAuthority.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_email
	 *
	 * @return the value of tbl_user_info.user_email
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_email
	 *
	 * @param userEmail the value for tbl_user_info.user_email
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_pass
	 *
	 * @return the value of tbl_user_info.user_pass
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserPass() {
		return userPass;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_pass
	 *
	 * @param userPass the value for tbl_user_info.user_pass
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserPass(String userPass) {
		this.userPass = userPass == null ? null : userPass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.user_department
	 *
	 * @return the value of tbl_user_info.user_department
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getUserDepartment() {
		return userDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.user_department
	 *
	 * @param userDepartment the value for tbl_user_info.user_department
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setUserDepartment(String userDepartment) {
		this.userDepartment = userDepartment == null ? null : userDepartment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.approver_id
	 *
	 * @return the value of tbl_user_info.approver_id
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getApproverId() {
		return approverId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.approver_id
	 *
	 * @param approverId the value for tbl_user_info.approver_id
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setApproverId(String approverId) {
		this.approverId = approverId == null ? null : approverId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.paid_vacation
	 *
	 * @return the value of tbl_user_info.paid_vacation
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public BigDecimal getPaidVacation() {
		return paidVacation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.paid_vacation
	 *
	 * @param paidVacation the value for tbl_user_info.paid_vacation
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setPaidVacation(BigDecimal paidVacation) {
		this.paidVacation = paidVacation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.rest_paid_vacation
	 *
	 * @return the value of tbl_user_info.rest_paid_vacation
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public BigDecimal getRestPaidVacation() {
		return restPaidVacation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.rest_paid_vacation
	 *
	 * @param restPaidVacation the value for tbl_user_info.rest_paid_vacation
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setRestPaidVacation(BigDecimal restPaidVacation) {
		this.restPaidVacation = restPaidVacation;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_user_info.delete_flg
	 *
	 * @return the value of tbl_user_info.delete_flg
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public String getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_user_info.delete_flg
	 *
	 * @param deleteFlg the value for tbl_user_info.delete_flg
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
	}
}