package com.example.attendance.entity;

import java.util.Date;

public class VacationApplyDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vacation_apply_detail.vacation_apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Long vacationApplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vacation_apply_detail.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Long applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vacation_apply_detail.target_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private Date targetDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vacation_apply_detail.vacation_type
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String vacationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vacation_apply_detail.applicant_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String applicantRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_vacation_apply_detail.approver_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    private String approverRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vacation_apply_detail.vacation_apply_id
     *
     * @return the value of tbl_vacation_apply_detail.vacation_apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Long getVacationApplyId() {
        return vacationApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vacation_apply_detail.vacation_apply_id
     *
     * @param vacationApplyId the value for tbl_vacation_apply_detail.vacation_apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setVacationApplyId(Long vacationApplyId) {
        this.vacationApplyId = vacationApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vacation_apply_detail.apply_id
     *
     * @return the value of tbl_vacation_apply_detail.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Long getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vacation_apply_detail.apply_id
     *
     * @param applyId the value for tbl_vacation_apply_detail.apply_id
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplyId(Long applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vacation_apply_detail.target_date
     *
     * @return the value of tbl_vacation_apply_detail.target_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Date getTargetDate() {
        return targetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vacation_apply_detail.target_date
     *
     * @param targetDate the value for tbl_vacation_apply_detail.target_date
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vacation_apply_detail.vacation_type
     *
     * @return the value of tbl_vacation_apply_detail.vacation_type
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getVacationType() {
        return vacationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vacation_apply_detail.vacation_type
     *
     * @param vacationType the value for tbl_vacation_apply_detail.vacation_type
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setVacationType(String vacationType) {
        this.vacationType = vacationType == null ? null : vacationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vacation_apply_detail.applicant_remark
     *
     * @return the value of tbl_vacation_apply_detail.applicant_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getApplicantRemark() {
        return applicantRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vacation_apply_detail.applicant_remark
     *
     * @param applicantRemark the value for tbl_vacation_apply_detail.applicant_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApplicantRemark(String applicantRemark) {
        this.applicantRemark = applicantRemark == null ? null : applicantRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_vacation_apply_detail.approver_remark
     *
     * @return the value of tbl_vacation_apply_detail.approver_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getApproverRemark() {
        return approverRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_vacation_apply_detail.approver_remark
     *
     * @param approverRemark the value for tbl_vacation_apply_detail.approver_remark
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setApproverRemark(String approverRemark) {
        this.approverRemark = approverRemark == null ? null : approverRemark.trim();
    }
}