package com.example.attendance.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VacationApplyDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public VacationApplyDetailExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andVacationApplyIdIsNull() {
            addCriterion("vacation_apply_id is null");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdIsNotNull() {
            addCriterion("vacation_apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdEqualTo(Long value) {
            addCriterion("vacation_apply_id =", value, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdNotEqualTo(Long value) {
            addCriterion("vacation_apply_id <>", value, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdGreaterThan(Long value) {
            addCriterion("vacation_apply_id >", value, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("vacation_apply_id >=", value, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdLessThan(Long value) {
            addCriterion("vacation_apply_id <", value, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdLessThanOrEqualTo(Long value) {
            addCriterion("vacation_apply_id <=", value, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdIn(List<Long> values) {
            addCriterion("vacation_apply_id in", values, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdNotIn(List<Long> values) {
            addCriterion("vacation_apply_id not in", values, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdBetween(Long value1, Long value2) {
            addCriterion("vacation_apply_id between", value1, value2, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andVacationApplyIdNotBetween(Long value1, Long value2) {
            addCriterion("vacation_apply_id not between", value1, value2, "vacationApplyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNull() {
            addCriterion("apply_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyIdIsNotNull() {
            addCriterion("apply_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyIdEqualTo(Long value) {
            addCriterion("apply_id =", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotEqualTo(Long value) {
            addCriterion("apply_id <>", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThan(Long value) {
            addCriterion("apply_id >", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("apply_id >=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThan(Long value) {
            addCriterion("apply_id <", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdLessThanOrEqualTo(Long value) {
            addCriterion("apply_id <=", value, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdIn(List<Long> values) {
            addCriterion("apply_id in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotIn(List<Long> values) {
            addCriterion("apply_id not in", values, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdBetween(Long value1, Long value2) {
            addCriterion("apply_id between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andApplyIdNotBetween(Long value1, Long value2) {
            addCriterion("apply_id not between", value1, value2, "applyId");
            return (Criteria) this;
        }

        public Criteria andTargetDateIsNull() {
            addCriterion("target_date is null");
            return (Criteria) this;
        }

        public Criteria andTargetDateIsNotNull() {
            addCriterion("target_date is not null");
            return (Criteria) this;
        }

        public Criteria andTargetDateEqualTo(Date value) {
            addCriterionForJDBCDate("target_date =", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("target_date <>", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateGreaterThan(Date value) {
            addCriterionForJDBCDate("target_date >", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("target_date >=", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateLessThan(Date value) {
            addCriterionForJDBCDate("target_date <", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("target_date <=", value, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateIn(List<Date> values) {
            addCriterionForJDBCDate("target_date in", values, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("target_date not in", values, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("target_date between", value1, value2, "targetDate");
            return (Criteria) this;
        }

        public Criteria andTargetDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("target_date not between", value1, value2, "targetDate");
            return (Criteria) this;
        }

        public Criteria andVacationTypeIsNull() {
            addCriterion("vacation_type is null");
            return (Criteria) this;
        }

        public Criteria andVacationTypeIsNotNull() {
            addCriterion("vacation_type is not null");
            return (Criteria) this;
        }

        public Criteria andVacationTypeEqualTo(String value) {
            addCriterion("vacation_type =", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotEqualTo(String value) {
            addCriterion("vacation_type <>", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeGreaterThan(String value) {
            addCriterion("vacation_type >", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("vacation_type >=", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeLessThan(String value) {
            addCriterion("vacation_type <", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeLessThanOrEqualTo(String value) {
            addCriterion("vacation_type <=", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeLike(String value) {
            addCriterion("vacation_type like", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotLike(String value) {
            addCriterion("vacation_type not like", value, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeIn(List<String> values) {
            addCriterion("vacation_type in", values, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotIn(List<String> values) {
            addCriterion("vacation_type not in", values, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeBetween(String value1, String value2) {
            addCriterion("vacation_type between", value1, value2, "vacationType");
            return (Criteria) this;
        }

        public Criteria andVacationTypeNotBetween(String value1, String value2) {
            addCriterion("vacation_type not between", value1, value2, "vacationType");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkIsNull() {
            addCriterion("applicant_remark is null");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkIsNotNull() {
            addCriterion("applicant_remark is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkEqualTo(String value) {
            addCriterion("applicant_remark =", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkNotEqualTo(String value) {
            addCriterion("applicant_remark <>", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkGreaterThan(String value) {
            addCriterion("applicant_remark >", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("applicant_remark >=", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkLessThan(String value) {
            addCriterion("applicant_remark <", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkLessThanOrEqualTo(String value) {
            addCriterion("applicant_remark <=", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkLike(String value) {
            addCriterion("applicant_remark like", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkNotLike(String value) {
            addCriterion("applicant_remark not like", value, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkIn(List<String> values) {
            addCriterion("applicant_remark in", values, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkNotIn(List<String> values) {
            addCriterion("applicant_remark not in", values, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkBetween(String value1, String value2) {
            addCriterion("applicant_remark between", value1, value2, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApplicantRemarkNotBetween(String value1, String value2) {
            addCriterion("applicant_remark not between", value1, value2, "applicantRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkIsNull() {
            addCriterion("approver_remark is null");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkIsNotNull() {
            addCriterion("approver_remark is not null");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkEqualTo(String value) {
            addCriterion("approver_remark =", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotEqualTo(String value) {
            addCriterion("approver_remark <>", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkGreaterThan(String value) {
            addCriterion("approver_remark >", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("approver_remark >=", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkLessThan(String value) {
            addCriterion("approver_remark <", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkLessThanOrEqualTo(String value) {
            addCriterion("approver_remark <=", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkLike(String value) {
            addCriterion("approver_remark like", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotLike(String value) {
            addCriterion("approver_remark not like", value, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkIn(List<String> values) {
            addCriterion("approver_remark in", values, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotIn(List<String> values) {
            addCriterion("approver_remark not in", values, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkBetween(String value1, String value2) {
            addCriterion("approver_remark between", value1, value2, "approverRemark");
            return (Criteria) this;
        }

        public Criteria andApproverRemarkNotBetween(String value1, String value2) {
            addCriterion("approver_remark not between", value1, value2, "approverRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 07 22:48:55 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbl_vacation_apply_detail
     *
     * @mbg.generated Mon Sep 07 22:48:55 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}