package com.example.attendance.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.attendance.dto.AS011Dto;
import com.example.attendance.dto.MonthApplyInsertDto;
import com.example.attendance.entity.Apply;
import com.example.attendance.entity.ApplyExample;

public interface ApplyMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	long countByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int deleteByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int deleteByPrimaryKey(Long applyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int insert(Apply row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int insertSelective(Apply row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	List<Apply> selectByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	Apply selectByPrimaryKey(Long applyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByExampleSelective(@Param("row") Apply row, @Param("example") ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByExample(@Param("row") Apply row, @Param("example") ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByPrimaryKeySelective(Apply row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_apply
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByPrimaryKey(Apply row);

	int insertApplyForVacation(Apply record);

	List<Apply> selectPendingApplications(String userId, int year, int month);

	int existsPendingMonthApplication(String userId, Long monthlyId);

	int insertApply(MonthApplyInsertDto dto);

	AS011Dto selectApplication(Long applyId);

	int approveApplication(Long applyId, String approverId);

	int returnApplication(Long applyId, String approverId);

}