package com.example.attendance.mapper;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.attendance.entity.DateState;
import com.example.attendance.entity.DateStateExample;

@Mapper
public interface DateStateMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	long countByExample(DateStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int deleteByExample(DateStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int deleteByPrimaryKey(Long dailyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int insert(DateState row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int insertSelective(DateState row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	List<DateState> selectByExample(DateStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	DateState selectByPrimaryKey(Long dailyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByExampleSelective(@Param("row") DateState row, @Param("example") DateStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByExample(@Param("row") DateState row, @Param("example") DateStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByPrimaryKeySelective(DateState row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_date_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByPrimaryKey(DateState row);

	List<DateState> selectCurrentAndPreviousMonth(String userId);

	DateState selectTodayByUserId(String userId);

	int updateClockIn(Long dailyId, LocalTime clockIn, Double latitude, Double longitude);

	int updateClockOut(Long dailyId, LocalTime clockOut, Double latitude, Double longitude);

	List<DateState> selectByUserIdAndYearMonth(String userId, Integer year, Integer month);

	DateState selectByUserIdAndTargetDate(String userId, LocalDate targetDate);

	int updateAttendance(Long dailyId, Date workStarttime, Date workEndtime, Integer workBreaktime,
			Integer workActualtime, Integer workOvertime, String editReason);

	Long selectMonthlyId(String userId, Integer year, Integer month);

	int insertAttendance(Long monthlyId, LocalDate targetDate, Date workStarttime, Date workEndtime,
			Integer workBreaktime, Integer workActualtime, Integer workOvertime, String editReason);

	int updateVacationState(Long dailyId, String workState);

	int insertVacationDateState(Long monthlyId, LocalDate targetDate, String workState);

	int insertDateStates(LocalDate targetDate);

	int updateVacationDateState(Long applyId, String state);

}