package com.example.attendance.mapper;

import java.time.LocalDate;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.attendance.entity.Holiday;
import com.example.attendance.entity.HolidayExample;

public interface HolidayMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	long countByExample(HolidayExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int deleteByExample(HolidayExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int deleteByPrimaryKey(Date holidayDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int insert(Holiday row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int insertSelective(Holiday row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	List<Holiday> selectByExample(HolidayExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	Holiday selectByPrimaryKey(Date holidayDate);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int updateByExampleSelective(@Param("row") Holiday row, @Param("example") HolidayExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int updateByExample(@Param("row") Holiday row, @Param("example") HolidayExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int updateByPrimaryKeySelective(Holiday row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table mst_holiday
	 *
	 * @mbg.generated Thu Sep 17 11:00:45 JST 2026
	 */
	int updateByPrimaryKey(Holiday row);

	int upsertHoliday(LocalDate holidayDate, String holidayName, String sourceType);
}