package com.example.attendance.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.attendance.dto.AS008Dto;
import com.example.attendance.entity.MonthState;
import com.example.attendance.entity.MonthStateExample;

@Mapper
public interface MonthStateMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	long countByExample(MonthStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int deleteByExample(MonthStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int deleteByPrimaryKey(Long monthlyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int insert(MonthState row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int insertSelective(MonthState row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	List<MonthState> selectByExample(MonthStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	MonthState selectByPrimaryKey(Long monthlyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByExampleSelective(@Param("row") MonthState row, @Param("example") MonthStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByExample(@Param("row") MonthState row, @Param("example") MonthStateExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByPrimaryKeySelective(MonthState row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_state
	 *
	 * @mbg.generated Mon Aug 17 20:46:17 JST 2026
	 */
	int updateByPrimaryKey(MonthState row);

	MonthState selectByUserIdAndYearMonth(String userId, short year, short month);

	List<MonthState> selectCurrentAndPreviousMonth(String userId);

	Long selectMonthlyId(String userId, Integer year, Integer month);

	int recalculateMonthState(Long monthlyId);

	int insertMonthStates(int year, int month);

	AS008Dto selectMonthlySummary(String userId, int year, int month);

	int updateMonthApplyState(Long monthlyId);

	int updateMonthState(Long applyId, String state);

}