package com.example.attendance.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.attendance.entity.MonthApplyDetail;
import com.example.attendance.entity.MonthApplyDetailExample;

public interface MonthApplyDetailMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	long countByExample(MonthApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int deleteByExample(MonthApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int deleteByPrimaryKey(Long monthApplyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int insert(MonthApplyDetail row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int insertSelective(MonthApplyDetail row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	List<MonthApplyDetail> selectByExample(MonthApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	MonthApplyDetail selectByPrimaryKey(Long monthApplyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByExampleSelective(@Param("row") MonthApplyDetail row, @Param("example") MonthApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByExample(@Param("row") MonthApplyDetail row, @Param("example") MonthApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByPrimaryKeySelective(MonthApplyDetail row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_month_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByPrimaryKey(MonthApplyDetail row);

	int insertMonthApplyDetail(Long applyId, Long monthlyId);

	int updateMonthRemark(Long applyId, String approverRemark);

}