package com.example.attendance.mapper;

import java.time.LocalDate;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.attendance.dto.AS009UserDto;
import com.example.attendance.entity.UserInfo;
import com.example.attendance.entity.UserInfoExample;

@Mapper
public interface UserInfoMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	long countByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int deleteByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int insert(UserInfo row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int insertSelective(UserInfo row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	List<UserInfo> selectByExample(UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	UserInfo selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int updateByExampleSelective(@Param("row") UserInfo row, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int updateByExample(@Param("row") UserInfo row, @Param("example") UserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int updateByPrimaryKeySelective(UserInfo row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_user_info
	 *
	 * @mbg.generated Fri Aug 14 15:55:23 JST 2026
	 */
	int updateByPrimaryKey(UserInfo row);

	UserInfo findByUserId(String userId);

	List<AS009UserDto> selectAdminUsers(String approverId, int year, int month, LocalDate startDate, LocalDate endDate);
}