package com.example.attendance.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.example.attendance.entity.VacationApplyDetail;
import com.example.attendance.entity.VacationApplyDetailExample;

public interface VacationApplyDetailMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	long countByExample(VacationApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int deleteByExample(VacationApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int deleteByPrimaryKey(Long vacationApplyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int insert(VacationApplyDetail row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int insertSelective(VacationApplyDetail row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	List<VacationApplyDetail> selectByExample(VacationApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	VacationApplyDetail selectByPrimaryKey(Long vacationApplyId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByExampleSelective(@Param("row") VacationApplyDetail row,
			@Param("example") VacationApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByExample(@Param("row") VacationApplyDetail row, @Param("example") VacationApplyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByPrimaryKeySelective(VacationApplyDetail row);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_vacation_apply_detail
	 *
	 * @mbg.generated Mon Sep 07 22:48:55 JST 2026
	 */
	int updateByPrimaryKey(VacationApplyDetail row);

	int insertVacationApply(VacationApplyDetail record);

	int updateVacationRemark(Long applyId, String approverRemark);

}